### ISSUE TITLE
Unable to install on Windows due to missing "git"

### ISSUE THREAD

**Issue by nordbjerg** [AtomLinter/Linter#114]
Hello. I can install all packages, except for yours.. and yours is really all I care about.

This is the log

```
npm http GET https://registry.npmjs.org/copy-paste
npm http GET https://registry.npmjs.org/font-awesome/4.0.3
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/xregexp/2.0.0
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/copy-paste
npm http 304 https://registry.npmjs.org/xregexp/2.0.0
npm http 304 https://registry.npmjs.org/font-awesome/4.0.3
npm http 304 https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/execSync
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/Benvie/harmony-collections.git) 
npm ERR! git clone https://github.com/Benvie/harmony-collections.git 
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/underscore-plus
npm ERR! Error: ENOENT, lstat 'C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936\node_modules\linter\node_modules\shelljs\src\common.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Oliver\\.atom\\.apmrc" "install" "C:\\Users\\Oliver\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.4.10\\package.tgz" "--target=0.11.10" "--arch=ia32" "--msvs_version=2012"
npm ERR! cwd C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936\node_modules\linter\node_modules\shelljs\src\common.js
npm ERR! fstream_path C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936\node_modules\linter\node_modules\shelljs\src\common.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936\node_modules\linter\node_modules\font-awesome\src\3.2.1\assets\font-awesome\css\font-awesome-ie7.min.css'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Oliver\\.atom\\.apmrc" "install" "C:\\Users\\Oliver\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.4.10\\package.tgz" "--target=0.11.10" "--arch=ia32" "--msvs_version=2012"
npm ERR! cwd C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936\node_modules\linter\node_modules\font-awesome\src\3.2.1\assets\font-awesome\css\font-awesome-ie7.min.css
npm ERR! fstream_path C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936\node_modules\linter\node_modules\font-awesome\src\3.2.1\assets\font-awesome\css\font-awesome-ie7.min.css
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936\node_modules\linter\node_modules\jshint\data\non-ascii-identifier-start.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Oliver\\.atom\\.apmrc" "install" "C:\\Users\\Oliver\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.4.10\\package.tgz" "--target=0.11.10" "--arch=ia32" "--msvs_version=2012"
npm ERR! cwd C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936\node_modules\linter\node_modules\jshint\data\non-ascii-identifier-start.js
npm ERR! fstream_path C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936\node_modules\linter\node_modules\jshint\data\non-ascii-identifier-start.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936\node_modules\linter\node_modules\lodash\dist\lodash.compat.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Oliver\\.atom\\.apmrc" "install" "C:\\Users\\Oliver\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.4.10\\package.tgz" "--target=0.11.10" "--arch=ia32" "--msvs_version=2012"
npm ERR! cwd C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936\node_modules\linter\node_modules\lodash\dist\lodash.compat.js
npm ERR! fstream_path C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936\node_modules\linter\node_modules\lodash\dist\lodash.compat.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/execSync
npm ERR! Error: spawn ENOENT
npm ERR!     at errnoException (child_process.js:988:11)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:779:34)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Oliver\\.atom\\.apmrc" "install" "C:\\Users\\Oliver\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.4.10\\package.tgz" "--target=0.11.10" "--arch=ia32" "--msvs_version=2012"
npm ERR! cwd C:\Users\Oliver\AppData\Local\Temp\apm-install-dir-114528-8256-1jo9936
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm WARN optional dep failed, continuing execSync@1.0.1-pre
npm
```

I am running ``v0.106.0-88df4d2`` of Atom on Windows 7. I have Visual Studio 2012 installed (with C++).

Any help appreciated.

**Comment by dmnd** [comment]
I'm closing this issue as it seems installing git fixes it.
