### ISSUE TITLE
Uncaught Error: No screen line exists when converting buffer row to screen row 

### ISSUE THREAD

**Issue by yeldarby** [AtomLinter/Linter#240]
I'm oftentimes getting an error and the stack trace is as follows:

	Uncaught Error: No screen line exists when converting buffer row to screen row /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:998
	module.exports.DisplayBuffer.screenPositionForBufferPosition /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:998
	module.exports.Marker.getHeadScreenPosition /Applications/Atom.app/Contents/Resources/app/src/marker.js:211
	Marker /Applications/Atom.app/Contents/Resources/app/src/marker.js:45
	module.exports.DisplayBuffer.getMarker /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1190
	module.exports.DisplayBuffer.markBufferRange /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1222
	module.exports.TextEditor.markBufferRange /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1198
	LinterView.display linter-view.coffee:180
	LinterView.processMessage linter-view.coffee:159
	(anonymous function) linter-view.coffee:1
	(anonymous function) linter-view.coffee:142
	Linter.processMessage linter.coffee:151
	(anonymous function) linter.coffee:127
	BufferedProcess.triggerExitCallback /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:52
	(anonymous function) /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:59
	(anonymous function) /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:105
	emit events.js:129(anonymous function) net.js:461

It's really obnoxious because when it gets into this state it keeps throwing the error (seems to happen whenever I hit Command+S to save) until I exit and reopen Atom.

**Comment by dmnd** [comment]
There hasn't been any more reports of this. Are you still experiencing it?

**Comment by yeldarby** [comment]
I haven't seen it in a while, closing for now; I'll re-open if it crops up again

**Comment by bradens** [comment]
I'm getting it again.

Not really sure how to repro it, but I've got a scss file open in one pane and js in 2 other panes. 

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.6


### Stack Trace

Uncaught Error: No screen line exists when converting buffer row to screen row

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1047

Error: No screen line exists when converting buffer row to screen row
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1047:17)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:174:33)
  at new Marker (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:34:41)
  at DisplayBuffer.module.exports.DisplayBuffer.getMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1265:20)
  at DisplayBuffer.module.exports.DisplayBuffer.handleBufferMarkerCreated (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1592:25)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.markerCreated (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1253:20)
  at MarkerStore.module.exports.MarkerStore.createMarker (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:313:21)
  at MarkerStore.module.exports.MarkerStore.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:148:19)
  at TextBuffer.module.exports.TextBuffer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:604:31)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1297:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1245:59)
  at LinterView.createMarker (/Users/braden/.atom/packages/linter/lib/linter-view.coffee:190:22)
  at LinterView.display (/Users/braden/.atom/packages/linter/lib/linter-view.coffee:227:17)
  at LinterView.processMessage (/Users/braden/.atom/packages/linter/lib/linter-view.coffee:178:8)
  at LinterView.processMessage (/Users/braden/.atom/packages/linter/lib/linter-view.coffee:1:1)
  at /Users/braden/.atom/packages/linter/lib/linter-view.coffee:164:14
  at LinterScssLint.Linter.processMessage (/Users/braden/.atom/packages/linter/lib/linter.coffee:241:5)
  at /Users/braden/.atom/packages/linter/lib/linter.coffee:173:8
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -1:27.7.0 atomic-emacs:previous-line (atom-text-editor.editor.kill-ring.is-focused)
  3x -1:27.5.0 atomic-emacs:next-line (atom-text-editor.editor.kill-ring.is-focused)
     -1:26.8.0 editor:move-to-end-of-line (atom-text-editor.editor.kill-ring.is-focused)
  2x -1:26.5.0 editor:newline (atom-text-editor.editor.kill-ring.is-focused)
  9x -1:21.9.0 core:backspace (atom-text-editor.editor.kill-ring.is-focused.autocomplete-active)
     -1:15.8.0 editor:newline (atom-text-editor.editor.kill-ring.is-focused)
     -1:14.1.0 atomic-emacs:next-line (atom-text-editor.editor.kill-ring.is-focused)
     -1:09.0 core:close (atom-text-editor.editor.kill-ring.is-focused)
     -1:08.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.kill-ring.is-focused)
     -1:06.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:06.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -1:05.7.0 atomic-emacs:next-line (atom-text-editor.editor.kill-ring.is-focused)
     -0:27.6.0 settings-view:open (atom-text-editor.editor.kill-ring.is-focused)
  2x -0:20.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:19.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.3.0 core:close (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "build"
    ],
    "themes": [
      "quantum-ui",
      "base16-tomorrow-dark-theme"
    ],
    "useReactEditor": true,
    "disabledPackages": [
      "editor-stats",
      "toggle-tabs",
      "term2",
      "sublime-tabs",
      "tabs",
      "emacs-mode",
      "terminal-status",
      "linter-jshint"
    ]
  },
  "linter": {
    "subtleLinterErrors": [
      "rubocop"
    ],
    "lintOnChangeInterval": 500,
    "ignoredLinterErrors": [
      "jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.6
atom-lint, v0.20.1
atomic-emacs, v0.5.1
custom-title, v0.7.1
emacs-mode, v0.0.29
language-haml, v0.20.0
linter, v0.12.6
linter-coffeelint, v0.2.4
linter-haml, v0.4.0
linter-rubocop, v0.2.7
linter-scss-lint, v1.0.4
linter-tidy, v1.0.1
pane-info, v1.0.0
pretty-json, v0.3.3
quantum-ui, v0.2.2
react, v0.11.8
tag, v0.3.0

# Dev
No dev packages
```
