### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by yemi** [AtomLinter/Linter#292]
Uncaught Error: spawn EACCES

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.0

### Steps To Reproduce

Happens everytime i open a .py file, i have linter-pep8 installed

### Stack Trace

```
At child_process.js:1160

Error: spawn EACCES
  at exports._errnoException (util.js:742:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at Object.exports.spawn (child_process.js:993:9)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:47:37)
  at LinterPep8.Linter.lintFile (/Users/fabianrios/.atom/packages/linter/lib/linter.coffee:142:19)
  at /Users/fabianrios/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/fabianrios/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

/cc @atom/core

**Comment by gatormha** [comment]
I was having this same issue with linter-pep8 and was able to fix it by changing my config from:
```
'linter-pep8':
    'pep8ExecutablePath': '/usr/local/bin'
```
to:
```
'linter-pep8':
    'pep8ExecutablePath': '/usr/local/bin/pep8'
```
Hopefully that helps you!

**Comment by yemi** [comment]
Thanks that solved the problem!
