### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of null

### ISSUE THREAD

**Issue by jackatbancast** [AtomLinter/Linter#300]
Uncaught TypeError: Cannot read property 'start' of null

**Atom Version**: 0.161.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.0

### Steps To Reproduce

1. Create file to be listed
2. Forget to leave a blank line below

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/range.js:26

TypeError: Cannot read property 'start' of null
  at Function.module.exports.Range.fromObject (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/range.js:26:31)
  at MarkerManager.module.exports.MarkerManager.markRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-manager.js:84:36)
  at TextBuffer.module.exports.TextBuffer.markRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:641:27)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1256:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1251:59)
  at LinterView.display (/Users/jack/.atom/packages/linter/lib/linter-view.coffee:179:26)
  at LinterView.processMessage (/Users/jack/.atom/packages/linter/lib/linter-view.coffee:156:6)
  at LinterView.processMessage (/Users/jack/.atom/packages/linter/lib/linter-view.coffee:1:1)
  at /Users/jack/.atom/packages/linter/lib/linter-view.coffee:139:14
  at LinterHLint.processMessage (/Users/jack/.atom/packages/linter-hlint/lib/linter-hlint.coffee:31:5)
  at /Users/jack/.atom/packages/linter/lib/linter.coffee:140:8
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:59:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:66:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:146:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:461:12)

```

/cc @atom/core

**Comment by park9140** [comment]
@athanclark, @jackatbancast , can't repro this,  can you let us know what linters you are running and specifically a file example where this is happening?

**Comment by dominikmayer** [comment]
I get the error messages when using hlint.

**Comment by Decoherence** [comment]
As a temporary workaround, disabling `Lint on Change` seems to resolve the issue while using `hlint`.

![linter_screen_shot](https://cloud.githubusercontent.com/assets/3780824/6320447/91b6bc5e-baab-11e4-9010-06c7234edb5b.png)

**Comment by jplatte** [comment]
I'm also getting this error with hlint, when writing new code in the last line of a file.

**Comment by rgscherf** [comment]
Same!

**Comment by iam4x** [comment]
Can you report this issue on the `linter-hslint` ?
