### ISSUE TITLE
Atom 0.165.0 + Linter 0.9.0 = Failed to activate

### ISSUE THREAD

**Issue by mrgamer** [AtomLinter/Linter#319]
I'm very new to Atom and package ecosystem, I hope it's a relevant bug:

```
Failed to activate package named 'linter' Error: The ::beforeRemove hook has been replaced by ::detached. See https://github.com/atom/space-pen#attacheddetached-hooks for details.
  at StatusBarView.View (c:\Users\valerio\.atom\packages\linter\node_modules\space-pen\lib\space-pen.js:150:15)
  at new StatusBarView (c:\Users\valerio\.atom\packages\linter\lib\statusbar-view.coffee:9:3)
  at LinterInitializer.activate (c:\Users\valerio\.atom\packages\linter\lib\init.coffee:70:26)
  at Package.module.exports.Package.activateNow (c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\src\package.js:227:27)
  at c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\src\package.js:213:28
  at Package.module.exports.Package.measure (c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\src\package.js:159:15)
  at Package.module.exports.Package.activate (c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\src\package.js:207:14)
  at PackageManager.module.exports.PackageManager.activatePackage (c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\src\package-manager.js:410:21)
  at c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\src\package-manager.js:396:33
  at Config.module.exports.Config.transact (c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\src\config.js:283:16)
  at PackageManager.module.exports.PackageManager.activatePackages (c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\src\package-manager.js:390:19)
  at PackageManager.module.exports.PackageManager.activate (c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\src\package-manager.js:379:19)
  at Atom.module.exports.Atom.startEditorWindow (c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\src\atom.js:605:21)
  at Object.<anonymous> (c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (c:\Users\valerio\AppData\Local\atom\app-0.165.0\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///C:/Users/valerio/AppData/Local/atom/app-0.165.0/resources/app/static/index.js:59:25)
```

Using Atom on windows x64 + Linter (0.9.0) installed from the Atom GUI

I see there's a branch to fix that already, and a commit: df03cd1ea4753d168dcf0b1d
Maybe keeping the issue open will keep the users know when it's resolved :+1:

**Comment by lagseeing** [comment]
How do i install that branch? im having that issue

**Comment by mrgamer** [comment]
Uninstall the manually installed package from APM, then do this:
`cd ~.atom/packages && git clone https://github.com/AtomLinter/Linter.git --branch fix-space-pen-deprication linter && cd ~.atom/packages/linter && npm install`

I think there's also another way with `apm`, but I don't know well the tool yet...

**Comment by anthonyraymond** [comment]
commenting the line 150 in :
`C:\Users\YOUR_USER_NAME\.atom\packages\linter\node_modules\space-pen\lib\space-pen.js`
temporary fix the issue : 

` // throw new Error("The ::beforeRemove hook has been replaced by ::detached. See https://github.com/atom/space-pen#attacheddetached-hooks for details.");`

**Comment by jonathandelgado** [comment]
This didn't effect me in 0.9.0, but I just updated to 0.9.1 and atom wouldn't even load properly due to this.

@anthonyraymond's temp fix worked for me.

**Comment by johngeorgewright** [comment]
Yep. I just got an update through for the linter package and everything's pretty buggered :cry:

**Comment by dmnd** [comment]
@park9140 I wonder if shipping space-pen 4.3.3 has made us dependent on Shadow DOM being enabled. People who had trouble with this issue, do you have Shadow DOM enabled in settings?

**Comment by yaroshevych** [comment]
I've have ShadowDOM enabled, and I've experienced this issue. At this moment it works fine.

**Comment by dmnd** [comment]
Can anyone encountering this report which version of space-pen they have installed at the time they experience the bug?

Here's how to do it:

```
$ cd ~/.atom/packages/linter
$ npm list space-pen
linter@0.9.1 /Users/dmnd/github/linter
└── space-pen@4.3.4 
```

You can see I have 4.3.4 installed. I don't experience the bug with this version.

**Comment by johngeorgewright** [comment]
Weird. I just re-installed linter and things seem to be ok now. I'm not using Shadow DOM and I also have space-pen@4.3.4.

**Comment by jonathandelgado** [comment]
@dmnd Just checked, I actually had sapce-pen@4.3.3 installed with linter@0.9.1 and atom@0.165.0 when the issue was occuring.

I just reinstalled the package and my space-pen version was incremented to 4.3.4, same as @johngeorgewright 

Looks like this was just a temp error, apm probably has the space-pen version cached somewhere?

+1 for close

**Comment by park9140** [comment]
@dmnd, just fyi, I do have shadow dom on, I have been testing most of the modules I work on in it for a few weeks.  Also, as of release https://github.com/atom/atom/releases/tag/v0.166.0 shadow dom is enabled by default.

**Comment by park9140** [comment]
Also release, 0.9.1 should have fixed this bug, it seems like there is something weird about how apm caches the actual running modules.  Seems like updating to 0.9.1 will not immediately load the new module version, `apm rebuild-module-cache` and restarting your editor will force this to happen.  We may need to think about opening an issue in atom.

**Comment by dmnd** [comment]
Good point @park9140, can you open that issue on Atom core?

I think we can probably close this issue now.
