### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by frequ** [AtomLinter/Linter#323]
Uncaught Error: This TextEditor has been destroyed

**Atom Version**: 0.161.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.7.3

### Steps To Reproduce

1. Writing JSON-object inside a JS-file.
2. On every save (cmd+s) I get this error.

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:989

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:989:15)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/marker.js:211:33)
  at new Marker (/Applications/Atom.app/Contents/Resources/app/src/marker.js:45:41)
  at DisplayBuffer.module.exports.DisplayBuffer.getMarker (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1224:20)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1256:19)
  at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1251:59)
  at LinterView.display (/Users/samppavalkama/.atom/packages/linter/lib/linter-view.coffee:180:26)
  at LinterView.processMessage (/Users/samppavalkama/.atom/packages/linter/lib/linter-view.coffee:159:6)
  at LinterView.processMessage (/Users/samppavalkama/.atom/packages/linter/lib/linter-view.coffee:1:1)
  at /Users/samppavalkama/.atom/packages/linter/lib/linter-view.coffee:142:14
  at LinterJshint.Linter.processMessage (/Users/samppavalkama/.atom/packages/linter/lib/linter.coffee:151:5)
  at /Users/samppavalkama/.atom/packages/linter/lib/linter.coffee:127:8
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:59:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:81:18)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

/cc @atom/core

**Comment by dmnd** [comment]
Please upgrade to the latest version
