### ISSUE TITLE
Linters not linting

### ISSUE THREAD

**Issue by AppoPro** [AtomLinter/Linter#324]
Failed to activate package named 'linter' Error: The ::beforeRemove hook has been replaced by ::detached. See https://github.com/atom/space-pen#attacheddetached-hooks for details.
  at StatusBarView.View (/home/appo/.atom/packages/linter/node_modules/space-pen/lib/space-pen.js:150:15)
  at new StatusBarView (/home/appo/.atom/packages/linter/lib/statusbar-view.coffee:9:3)
  at LinterInitializer.activate (/home/appo/.atom/packages/linter/lib/init.coffee:70:26)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:227:27)
  at /usr/share/atom/resources/app/src/package.js:213:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:159:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:207:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:410:21)
  at /usr/share/atom/resources/app/src/package-manager.js:396:33
  at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:283:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:390:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:379:19)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:605:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:59:25)

**Comment by dmnd** [comment]
This was fixed by #318, please upgrade.
