### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory 'rustc'

### ISSUE THREAD

**Issue by elbow-jason** [AtomLinter/Linter#330]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.11.0-12-generic
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory 'rustc'

```
At fs.js:726

Error: ENOENT, no such file or directory 'rustc'
  at Error (native)
  at fs.statSync (fs.js:726:18)
  at Object.fs.statSync (/usr/share/atom/resources/atom/common/lib/asar.js:155:14)
  at LinterRust.<anonymous> (/home/elbow/.atom/packages/linter/lib/linter.coffee:56:8)
  at LinterRust.memoized [as _cachedStatSync] (/usr/share/atom/resources/app/node_modules/roaster/node_modules/cheerio/node_modules/lodash/dist/lodash.js:5569:32)
  at LinterRust.Linter.getCmdAndArgs (/home/elbow/.atom/packages/linter/lib/linter.coffee:71:16)
  at LinterRust.Linter.lintFile (/home/elbow/.atom/packages/linter/lib/linter.coffee:112:24)
  at LinterRust.lintFile (/home/elbow/.atom/packages/linter-rust/lib/linter-rust.coffee:42:7)
  at LinterRust.lintFile (/home/elbow/.atom/packages/linter-rust/lib/linter-rust.coffee:1:1)
  at /home/elbow/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /home/elbow/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -0:20.6 tree-view:remove (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -0:11.8 application:new-file (input.hidden-input)
     -0:01.0 core:paste (input.hidden-input)
     -0:00.0 core:save (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
build, v0.21.0
elixir-cmd, v0.2.3
language-elixir, v0.3.3
language-rust, v0.3.2
linter, v0.9.0
linter-elixirc, v0.2.1
linter-rust, v0.0.3
minimap, v3.4.9
monokai, v0.9.0
racer, v0.8.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by elbow-jason** [comment]
Also...

❯❯❯ rustc --version                                          ⏎ ✱ ◼ (git:master)
rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800)

**Comment by m-bra** [comment]
Affects me too, rustc --version:
rustc 0.13.0-nightly (96a3c7c6a 2014-12-23 22:21:10 +0000)

**Comment by dmnd** [comment]
Please see #150 - are you guys starting Atom from the command line?

**Comment by elbow-jason** [comment]
Yes I am starting atom from the command line.

**Comment by m-bra** [comment]
Nope

**Comment by elbow-jason** [comment]
Additionally, this occurs via command line atom and gui icon atom.

**Comment by rwhite226** [comment]
I can also confirm this on 
atom 0.181.0
rustc 1.0.0-nightly (6c065fc8c 2015-02-17) (built 2015-02-18)
and Linux 3.18.7-2

**Comment by lee8oi** [comment]
[Enter steps to reproduce below:]

1. Start Atom
2. Select a *.rs file.

**Atom Version**: 0.184.0-5aaf3ef
**System**: linux 3.18.6-1-ARCH
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory 'rustc'

```
At /usr/share/atom/resources/atom/common/lib/asar.js:52

Error: ENOENT, no such file or directory 'rustc'
  at Error (native)
  at fs.statSync (fs.js:807:18)
  at Object.fs.statSync (/usr/share/atom/resources/atom/common/lib/asar.js:155:14)
  at LinterRust.Linter._cachedStatSync (/home/lee8oi/.atom/packages/linter/lib/linter.coffee:69:17)
  at LinterRust.Linter.getCmdAndArgs (/home/lee8oi/.atom/packages/linter/lib/linter.coffee:86:16)
  at LinterRust.Linter.lintFile (/home/lee8oi/.atom/packages/linter/lib/linter.coffee:127:24)
  at LinterRust.lintFile (/home/lee8oi/.atom/packages/linter-rust/lib/linter-rust.coffee:42:7)
  at LinterRust.lintFile (/home/lee8oi/.atom/packages/linter-rust/lib/linter-rust.coffee:1:1)
  at /home/lee8oi/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /home/lee8oi/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
```

### Config

```json
{
  "linter": {}
}
```

### Installed Packages

```coffee
# User
language-rust, v0.4.2
linter, v0.12.0
linter-rust, v0.0.3
racer, v0.9.1

# Dev
No dev packages
```

**Comment by glennpratt** [comment]
Saw the same error and set the path:

```
/Users/glenn.pratt/opt/rust-dev/bin/rustc
```

Now I don't see the error at startup, but it still doesn't seem to work.

**Comment by rustedwolf** [comment]
Atom 0.187.0 (build without sudo)
linter-rust, v0.0.6
rustc 1.0.0-nightly
Still doesn't work.
