### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by albertvilacalvo** [AtomLinter/Linter#338]
After launching Atom with the command line (atom .), there was a pop-up asking me to submit an issue. I checked the other issues and I didn't find any duplicate. The following was added automatically by Atom (except the steps):

[Enter steps to reproduce below:]

1. Open terminal
2. Type 'atom .'

**Atom Version**: 0.172.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.1

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJshint.Linter.getNodeExecutablePath (/Users/albertvilacalvo/.atom/packages/linter/lib/linter.coffee:114:10)
  at LinterJshint.Linter.getCmdAndArgs (/Users/albertvilacalvo/.atom/packages/linter/lib/linter.coffee:90:25)
  at LinterJshint.Linter.lintFile (/Users/albertvilacalvo/.atom/packages/linter/lib/linter.coffee:122:24)
  at /Users/albertvilacalvo/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/albertvilacalvo/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
css-color-highlight, v0.3.0
file-icons, v1.4.4
linter, v0.9.1
linter-csslint, v0.0.11
linter-jshint, v0.1.0
monokai, v0.9.0
scroll-past-end, v0.1.9

# Dev
No dev packages
```

/cc @atom/core

**Comment by albertvilacalvo** [comment]
OK. It is a duplicate of #329
