### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by slava-viktorov** [AtomLinter/Linter#359]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: linux 3.17.1-52.g5c4d099-desktop
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.1

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJscs.Linter.getNodeExecutablePath (/home/slava/.atom/packages/linter/lib/linter.coffee:114:10)
  at LinterJscs.Linter.getCmdAndArgs (/home/slava/.atom/packages/linter/lib/linter.coffee:90:25)
  at LinterJscs.Linter.lintFile (/home/slava/.atom/packages/linter/lib/linter.coffee:122:24)
  at /home/slava/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /home/slava/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-flow",
      "Remote-FTP",
      "remote-edit",
      "remote-sync",
      "SFTP-deployment",
      "language-javascript-subtlegradient",
      "atom-jshint"
    ]
  },
  "linter": {
    "showErrorInline": true
  }
}
```

### Installed Packages

```coffee
# User
atom-deconsole, v0.0.1
atom-ternjs, v0.2.6
autocomplete-plus, v1.1.0
emmet, v2.3.0
file-icons, v1.4.4
gulp-snippets, v0.6.0
javascript-snippets, v1.0.0
js-refactor, v0.3.0
jsformat, v0.7.18
language-javascript-semantic, v0.1.0
linter, v0.9.1
linter-csslint, v0.0.11
linter-jscs, v1.4.9
linter-jshint, v0.1.0
refactor, v0.4.1
remote-atom, v1.1.10
scope-inspector, v0.2.1
script, v2.16.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by stringparser** [comment]
same here

**Comment by dmnd** [comment]
This bug is already fixed; please upgrade your linter package

**Comment by stringparser** [comment]
thanks @dmnd
