### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by s905060** [AtomLinter/Linter#365]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.10.0

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At child_process.js:1156

Error: spawn ENOTDIR
  at exports._errnoException (util.js:746:11)
  at ChildProcess.spawn (child_process.js:1156:11)
  at Object.exports.spawn (child_process.js:989:9)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:51:37)
  at LinterPylint.Linter.lintFile (/Users/jashl/.atom/packages/linter/lib/linter.coffee:152:19)
  at /Users/jashl/.atom/packages/linter/lib/linter-view.coffee:139:18
  at Array.forEach (native)
  at /Users/jashl/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -0:00.5 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-seti-ui)
     -0:00.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai"
    ]
  },
  "linter": {
    "showErrorInline": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.2
atom-django, v0.2.0
atom-lint, v0.20.1
autocomplete-plus, v1.1.0
color-picker, v1.4.0
highlight-selected, v0.7.0
language-python-django-templates, v0.1.0
linter, v0.10.0
linter-clang, v2.10.0
linter-csslint, v0.0.11
linter-javac, v0.1.3
linter-php, v0.0.11
linter-pylint, v0.2.0
linter-shellcheck, v0.0.6
linter-xmllint, v0.0.5
minimap, v3.5.6
minimap-selection, v3.1.1
monokai, v0.9.0
seti-ui, v0.6.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by sanderv32** [comment]
Also have this error on Ubuntu 14.04LTS. Already added

<code>process.env.PATH = ["/usr/bin", process.env.PATH].join(":")</code>

to the init.coffee but that doesn't solve this problem.

**Comment by Tylerlhess** [comment]
My stack trace is a little different.

child_process.js:1160
Hide Stack TraceShow Stack Trace
Error: spawn ENOTDIR
  at exports._errnoException (util.js:753:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at Object.exports.spawn (child_process.js:993:9)
  at new BufferedProcess (/Users/****/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:51:37)
  at LinterPylint.Linter.lintFile (/Users/****/.atom/packages/linter/lib/linter.coffee:152:19)
  at /Users/tyler.hess/.atom/packages/linter/lib/linter-view.coffee:150:18
  at Array.forEach (native)
  at /Users/****/.atom/packages/linter/lib/linter-view.coffee:149:18
  at FSReqWrap.oncomplete (fs.js:100:15)

**Comment by escolhatecnologia** [comment]
/usr/share/atom/resources/app.asar/src/buffered-process.js:260
 
Error: spawn ENOTDIR
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
  at LinterJshint.Linter.lintFile (/home/victorhugo/.atom/packages/linter/lib/linter.coffee:160:19)
  at /home/victorhugo/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /home/victorhugo/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

**Comment by JoeNoPhoto** [comment]
Error: spawn ENOTDIR
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/Users//Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/Users//Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at LinterJshint.Linter.lintFile (/Users//.atom/packages/linter/lib/linter.coffee:178:19)
  at LinterJshint.lintFile (/Users//.atom/packages/linter-jshint/lib/linter-jshint.coffee:56:5)
  at /Users//.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users//.atom/packages/linter/lib/linter-view.coffee:162:18

**Comment by seanwash** [comment]
I see that this issue has been closed, but Im still getting this error and Atom doesn't report that I have any plugins that need updating.

**Comment by AsaAyers** [comment]
Linter was completely rewritten. I closed all 157 issues and this was one of them. 

If it's still an issue please open a new issue with steps to reproduce.

**Comment by seanwash** [comment]
Got it! I'll open a new issue. Thanks for your awesome work btw.
