### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by lucasdavila** [AtomLinter/Linter#381]
[Enter steps to reproduce below:]

1. Upgraded atom to version 0.175.0
2. Initialised atom inside my project's directory.

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.7.3

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJshint.Linter.getNodeExecutablePath (/Users/lucasdavila/.atom/packages/linter/lib/linter.coffee:99:10)
  at LinterJshint.Linter.getCmdAndArgs (/Users/lucasdavila/.atom/packages/linter/lib/linter.coffee:80:25)
  at LinterJshint.Linter.lintFile (/Users/lucasdavila/.atom/packages/linter/lib/linter.coffee:107:24)
  at /Users/lucasdavila/.atom/packages/linter/lib/linter-view.coffee:141:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-scss-lint",
      "linter-rubocop"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.12.0
autocomplete-plus, v0.22.1
color-picker, v1.2.6
linter, v0.7.3
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-php, v0.0.11
script, v2.13.0
tabs-to-spaces, v0.7.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment]
Please upgrade to the latest version, this bug is already fixed :smile:

**Comment by lucasdavila** [comment]
Thank you.
