### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by miketamis** [AtomLinter/Linter#389]
After installing Linter and Linter-jshint, I try to open a .js file, and it has this error and doesnt let me see my js file.

**Atom Version**: 0.169.0
**System**: linux 3.13.0-32-generic
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.10.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app/node_modules/q/q.js:126

TypeError: undefined is not a function
  at LinterJshint.Linter (/home/mrtemp/.atom/packages/linter/lib/linter.coffee:54:33)
  at new LinterJshint (/home/mrtemp/.atom/packages/linter-jshint/lib/linter-jshint.coffee:28:5)
  at LinterView.initLinters (/home/mrtemp/.atom/packages/linter/lib/linter-view.coffee:51:27)
  at new LinterView (/home/mrtemp/.atom/packages/linter/lib/linter-view.coffee:33:6)
  at /home/mrtemp/.atom/packages/linter/lib/init.coffee:83:24
  at /usr/share/atom/resources/app/src/workspace.js:273:16
  at /usr/share/atom/resources/app/src/workspace.js:330:18
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app/src/pane-container.js:379:27)
  at /usr/share/atom/resources/app/src/pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:334:20)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:313:14)
  at /usr/share/atom/resources/app/src/workspace.js:497:16
  at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:749:13)
  at /usr/share/atom/resources/app/node_modules/q/q.js:557:44
  at flush (/usr/share/atom/resources/app/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
     -0:03.3 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "linter-flow"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "linter": {
    "showErrorInline": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
autocomplete-snippets, v0.3.2
color-picker, v1.2.6
git-log, v0.2.0
highlight-line, v0.9.3
linter, v0.10.1
linter-jshint, v0.1.0
minimap, v3.5.4
minimap-git-diff, v3.1.0
pretty-json, v0.3.2
tabs-to-spaces, v0.8.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by m-bra** [comment]
Same here with linter-clang, the linter fails to call editor.getURI because this function does not exist [anymore], i think. Maybe it should be replaced with getPath().

**Comment by m-bra** [comment]
Made PR which fixes the problem.

**Comment by dmnd** [comment]
Closing this in favour of #391.

Please upgrade Atom if you are experiencing this error, it doesn't occur in the latest release.

**Comment by dmnd** [comment]
@hd-deman ?
