### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by miketamis** [AtomLinter/Linter#405]
**Atom Version**: 0.169.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.10.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app/node_modules/q/q.js:126

TypeError: undefined is not a function
  at LinterPylint.Linter (/home/mrtemp/.atom/packages/linter/lib/linter.coffee:54:33)
  at new LinterPylint (/home/mrtemp/.atom/packages/linter-pylint/lib/linter-pylint.coffee:18:5)
  at LinterView.initLinters (/home/mrtemp/.atom/packages/linter/lib/linter-view.coffee:51:27)
  at new LinterView (/home/mrtemp/.atom/packages/linter/lib/linter-view.coffee:33:6)
  at /home/mrtemp/.atom/packages/linter/lib/init.coffee:83:24
  at /usr/share/atom/resources/app/src/workspace.js:273:16
  at /usr/share/atom/resources/app/src/workspace.js:330:18
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app/src/pane-container.js:379:27)
  at /usr/share/atom/resources/app/src/pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:334:20)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:313:14)
  at /usr/share/atom/resources/app/src/workspace.js:497:16
  at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:749:13)
  at /usr/share/atom/resources/app/node_modules/q/q.js:557:44
  at flush (/usr/share/atom/resources/app/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
     -7:29.9 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -7:29.9 snippets:expand (atom-text-editor.editor.is-focused)
     -7:29.9 editor:indent (atom-text-editor.editor.is-focused)
     -7:27.1 core:undo (atom-text-editor.editor.is-focused)
     -0:03.4 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:00.6 core:backspace (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-flow"
    ]
  },
  "linter": {
    "lintDebug": true,
    "showErrorInline": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-emojis, v0.7.1
autocomplete-paths, v1.0.1
autocomplete-plus, v2.0.6
autocomplete-plus-jedi, v0.0.4
autocomplete-snippets, v1.0.0
language-log, v0.0.1
linter, v0.10.1
linter-jscs, v1.4.9
linter-pylint, v0.2.0
minimap, v3.5.6
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
minimap-selection, v3.1.1
revert-buffer, v0.4.0
view-tail-large-files, v0.1.8

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment]
Sorry I think this is an incompatibility between linter 0.10.1 and Atom 0.169.0. Please upgrade your copy of Atom!
