### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

### ISSUE THREAD

**Issue by jelmerdemaat** [AtomLinter/Linter#407]
1. Have linter + linter-php installed
2. In a PHP file, choose "Linter: next message" (from Package Control or with the shortcut ` Ctrl + K - Down`
3. Linter does not do anything and an error is thrown.

The following was the error, seems an issue was not yet created.

**Atom Version**: 0.176.0
**System**: linux 3.2.0-75-generic
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

```
At /usr/share/atom/resources/app/src/text-editor.js:1339

TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (/usr/share/atom/resources/app/src/text-editor.js:1339:34)
  at LinterView.moveToNextMessage (/home/jelmer/.atom/packages/linter/lib/linter-view.coffee:234:26)
  at atom-text-editor.<anonymous> (/home/jelmer/.atom/packages/linter/lib/linter-view.coffee:126:34)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:56.1 core:save (atom-text-editor.editor.is-focused)
     -0:37.1 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:30.3 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:29.4 core:confirm (atom-text-editor.editor.mini)
     -0:29.3 linter:lint (atom-text-editor.editor.is-focused)
     -0:27.7 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:26.0 core:move-down (atom-text-editor.editor.mini)
     -0:24.6 core:confirm (atom-text-editor.editor.mini)
     -0:24.5 linter:next-message (atom-text-editor.editor.is-focused)
     -0:14.1 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:12.6 core:move-down (atom-text-editor.editor.mini)
     -0:11.6 core:move-up (atom-text-editor.editor.mini)
     -0:08.8 core:confirm (atom-text-editor.editor.mini)
     -0:08.8 linter:next-message (atom-text-editor.editor.is-focused)
     -0:04.5 pane:split-down (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:00.6 linter:next-message (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
advanced-new-file, v0.2.1
browser-refresh, v0.8.3
linter, v0.11.0
linter-php, v0.0.11
minimap, v3.5.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment]
Interesting. I just implemented that command yesterday so it's brand new. Thanks for trying it out :smile: 

Does the command work for you at all, or was error an edge case? If this error was an edge case, was there anything unusual about the file you were trying to navigate?

**Comment by dmnd** [comment]
Thanks for reporting, fixed in the next release.

**Comment by jelmerdemaat** [comment]
Sorry for late response, I tested it again, seem to be working well now on Windows, will test on Linux later!

**Comment by bronson** [comment]
Strange.  I just got this error when switching branches.

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.2.4


### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1321:34)
  at MessageRegistry.getActiveFileMessagesForActiveRow (/Users/bronson/.atom/packages/linter/lib/messages.coffee:77:12)
  at LinterViews.updateLineMessages (/Users/bronson/.atom/packages/linter/lib/linter-views.coffee:110:38)
  at /Users/bronson/.atom/packages/linter/lib/editor-linter.coffee:23:25
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.cursorMoved (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1591:27)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/cursor.js:56:31
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/marker.js:270:27)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/marker.js:65:26
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:401:20)
  at MarkerStore.module.exports.MarkerStore.createSnapshot (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:232:20)
  at TextBuffer.module.exports.TextBuffer.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:762:83)
  at TextBuffer.module.exports.TextBuffer.setTextViaDiff (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:480:19)
  at TextBuffer.module.exports.TextBuffer.reload (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1019:12)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1143:26
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:439:40
  at _fulfilled (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "exception-reporting",
      "wrap-guide",
      "welcome",
      "background-tips",
      "linter-rubocop",
      "package-cop",
      "linter-haml",
      "smart-tab-name",
      "linter-eslint",
      "linter-jscs",
      "linter-jshint",
      "vim-mode",
      "table-edit"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-reef-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "linter": {
    "subtleLinterErrors": [
      "haml-lint"
    ],
    "lintOnFly": false
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.7.1
color-picker, v2.0.11
cursor-history, v0.4.15
file-icons, v1.6.2
git-log, v0.4.1
highlight-selected, v0.10.1
language-haml, v0.21.0
linter, v1.2.4
linter-coffeelint, v1.0.1
linter-csslint, v0.0.14
linter-erb, v0.1.1
linter-ruby, v0.1.6
oceanic-reef-syntax, v0.6.0
react, v0.12.6
vim-mode-next, v0.57.0
vim-mode-visual-block, v0.2.13
vim-surround, v0.8.0
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by bronson** [comment]
Just  happened again, seems pretty reliable.  Should this issue be reopened?  Or I can file a new one.
