### ISSUE TITLE
Uncaught Error: spawn EBADF

### ISSUE THREAD

**Issue by Cipa** [AtomLinter/Linter#423]
[Enter steps to reproduce below:]

1. I tried to save a file for a project opened from a mounted disk. The error appeared together with https://github.com/atom/atom/issues/5518

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.11.1

### Stack Trace

Uncaught Error: spawn EBADF

```
At child_process.js:1160

Error: spawn EBADF
  at exports._errnoException (util.js:753:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at Object.exports.spawn (child_process.js:993:9)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:51:37)
  at LinterJshint.Linter.lintFile (/Users/ciMac/.atom/packages/linter/lib/linter.coffee:152:19)
  at /Users/ciMac/.atom/packages/linter/lib/linter-view.coffee:150:18
  at Array.forEach (native)
  at /Users/ciMac/.atom/packages/linter/lib/linter-view.coffee:149:18
  at FSReqWrap.oncomplete (fs.js:100:15)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as isMaximized] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom.js:506:33)
  at Atom.module.exports.Atom.storeDefaultWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom.js:537:25)
  at /Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:97:21
  at handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -0:19.8 editor:indent (atom-text-editor.editor)
     -0:19.2 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:19.2 editor:newline (atom-text-editor.editor)
     -0:19.1 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:19.1 editor:newline (atom-text-editor.editor)
     -0:18.9 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:18.9 editor:newline (atom-text-editor.editor)
     -0:18.8 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:18.8 editor:newline (atom-text-editor.editor)
  3x -0:18.4 core:move-up (atom-text-editor.editor)
     -0:17.9 core:paste (atom-text-editor.editor)
     -0:14.9 emmet:toggle-comment (atom-text-editor.editor)
     -0:14.9 editor:toggle-line-comments (atom-text-editor.editor)
     -0:11.6 core:copy (atom-text-editor.editor)
     -0:09.8 core:paste (atom-text-editor.editor)
     -0:08.6 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.21.3
atom-ctags, v2.6.0
autoclose-html, v0.15.0
emmet, v2.3.3
highlight-selected, v0.7.0
html-entities, v0.3.1
less-autocompile, v0.3.3
linter, v0.11.1
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-less, v0.3.1
linter-php, v0.0.11
red-wavy-underline, v0.2.4
todo-show, v0.8.0
white-cursor, v0.5.2

# Dev
No dev packages
```

**Comment by Cipa** [comment]
It happened because the disk was not available anymore. Maybe a warning could be added when this happens
