### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory 'C:\Users\Jason\AppData\Local\atom\app-0.182.0\rustc'

### ISSUE THREAD

**Issue by jason-kerney** [AtomLinter/Linter#439]
[Enter steps to reproduce below:]

1. Open rust file

**Atom Version**: 0.182.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.11.1

### Stack Trace

Uncaught Error: ENOENT, no such file or directory 'C:\Users\Jason\AppData\Local\atom\app-0.182.0\rustc'

```
At fs.js:807

Error: ENOENT, no such file or directory 'C:\Users\Jason\AppData\Local\atom\app-0.182.0\rustc'
  at Error (native)
  at fs.statSync (fs.js:807:18)
  at Object.fs.statSync (C:\Users\Jason\AppData\Local\atom\app-0.182.0\resources\atom\common\lib\asar.js:155:14)
  at LinterRust.<anonymous> (C:\Users\Jason\.atom\packages\linter\lib\linter.coffee:66:8)
  at LinterRust.memoized [as _cachedStatSync] (C:\Users\Jason\AppData\Local\atom\app-0.182.0\resources\app\node_modules\cheerio\node_modules\lodash\dist\lodash.js:5569:32)
  at LinterRust.Linter.getCmdAndArgs (C:\Users\Jason\.atom\packages\linter\lib\linter.coffee:81:16)
  at LinterRust.Linter.lintFile (C:\Users\Jason\.atom\packages\linter\lib\linter.coffee:122:24)
  at LinterRust.lintFile (C:\Users\Jason\.atom\packages\linter-rust\lib\linter-rust.coffee:42:7)
  at LinterRust.lintFile (C:\Users\Jason\.atom\packages\linter-rust\lib\linter-rust.coffee:1:1)
  at C:\Users\Jason\.atom\packages\linter\lib\linter-view.coffee:150:18
  at Array.forEach (native)
  at C:\Users\Jason\.atom\packages\linter\lib\linter-view.coffee:149:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -0:58.4 pane:reopen-closed-item (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {},
  "linter": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.2.0
color-picker, v1.4.4
elixir-cmd, v0.2.3
go-plus, v3.2.2
go-rename, v0.3.0
language-elixir, v0.3.3
language-fsharp, v0.8.4
language-lisp, v0.1.1
language-rust, v0.4.1
linter, v0.11.1
linter-elixirc, v0.2.1
linter-rust, v0.0.3
racer, v0.9.1
script-runner, v1.7.0

# Dev
No dev packages
```

**Comment by iam4x** [comment]
Seems more an error with https://github.com/AtomLinter/linter-rust

**Comment by gmist** [comment]
Is this still relevant with latest [linter-rust](https://github.com/AtomLinter/linter-rust)?
