### ISSUE TITLE
Uncaught Error: spawn UnknownSystemError

### ISSUE THREAD

**Issue by thoughtassassin** [AtomLinter/Linter#447]
[Enter steps to reproduce below:]

1.Save a file with .html extension

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.11.1

### Stack Trace

Uncaught Error: spawn UnknownSystemError

```
At child_process.js:1160

Error: spawn UnknownSystemError
  at exports._errnoException (util.js:753:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at Object.exports.spawn (child_process.js:993:9)
  at new BufferedProcess (/Applications/UX Apps/Atom.app/Contents/Resources/app/src/buffered-process.js:51:37)
  at LinterTidy.Linter.lintFile (/Users/david/.atom/packages/linter/lib/linter.coffee:152:19)
  at /Users/david/.atom/packages/linter/lib/linter-view.coffee:150:18
  at Array.forEach (native)
  at /Users/david/.atom/packages/linter/lib/linter-view.coffee:149:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
  3x -2:41.1 editor:newline (atom-text-editor.editor)
 37x -2:26.1 core:backspace (atom-text-editor.editor)
     -2:05.9 snippets:next-tab-stop (atom-text-editor.editor)
     -2:05.9 snippets:expand (atom-text-editor.editor)
     -2:05.9 editor:indent (atom-text-editor.editor)
  2x -2:03.3 editor:newline (atom-text-editor.editor)
     -1:56.7 snippets:next-tab-stop (atom-text-editor.editor)
     -1:56.7 snippets:expand (atom-text-editor.editor)
     -1:56.7 editor:indent (atom-text-editor.editor)
     -1:55.3 snippets:next-tab-stop (atom-text-editor.editor)
     -1:55.3 snippets:expand (atom-text-editor.editor)
     -1:55.3 editor:indent (atom-text-editor.editor)
     -1:54.1 snippets:next-tab-stop (atom-text-editor.editor)
     -1:54.1 snippets:expand (atom-text-editor.editor)
     -1:54.1 editor:indent (atom-text-editor.editor)
     -1:09.4 core:save-as (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter-phpmd",
      "linter-phpcs"
    ]
  },
  "linter": {
    "showInfoMessages": true
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.11.1
linter-csslint, v0.0.11
linter-haml, v0.1.1
linter-htmlhint, v0.0.8
linter-jshint, v0.1.0
linter-php, v0.0.11
linter-scss-lint, v0.0.14
linter-tidy, v1.0.0

# Dev
No dev packages
```

**Comment by iam4x** [comment]
Seems more an error with https://github.com/AtomLinter/linter-tidy

**Comment by corysimmons** [comment]
Agreed, this seems like a problem with Tidy.
