### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory 'C:\Users\Jacob\Go\bin\golint'

### ISSUE THREAD

**Issue by jacobsantos** [AtomLinter/Linter#461]
1. Create new file.
2. Name file "main.go"

**Atom Version**: 0.186.0
**System**: Microsoft Windows 8.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory 'C:\Users\Jacob\Go\bin\golint'

```
At fs.js:807

Error: ENOENT, no such file or directory 'C:\Users\Jacob\Go\bin\golint'
  at Error (native)
  at fs.statSync (fs.js:807:18)
  at Object.fs.statSync (C:\Users\Jacob\AppData\Local\atom\app-0.186.0\resources\atom\common\lib\asar.js:155:14)
  at LinterGolint.Linter._cachedStatSync (C:\Users\Jacob\.atom\packages\linter\lib\linter.coffee:69:17)
  at LinterGolint.Linter.getCmdAndArgs (C:\Users\Jacob\.atom\packages\linter\lib\linter.coffee:86:16)
  at LinterGolint.Linter.lintFile (C:\Users\Jacob\.atom\packages\linter\lib\linter.coffee:127:24)
  at C:\Users\Jacob\.atom\packages\linter\lib\linter-view.coffee:158:18
  at Array.forEach (native)
  at C:\Users\Jacob\.atom\packages\linter\lib\linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -3:23.3 core:confirm (atom-text-editor.editor.mini)
  3x -3:17.7 core:backspace (atom-text-editor.editor.is-focused)
     -3:13.6 core:move-right (atom-text-editor.editor.is-focused)
  2x -3:12.6 editor:newline (atom-text-editor.editor.is-focused)
     -3:09.3 core:save (atom-text-editor.editor.is-focused)
     -2:50.2 core:backspace (atom-text-editor.editor.is-focused)
  4x -2:49.4 core:move-right (atom-text-editor.editor.is-focused)
     -2:48.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:46.1 core:save (atom-text-editor.editor.is-focused)
     -2:28.6 golang:goinfo (atom-text-editor.editor.is-focused)
     -1:03.3 core:paste (atom-text-editor#go-plus.goPath.editor.mini)
     -1:01.4 core:save (atom-text-editor#go-plus.goPath.editor.mini)
     -0:32.6 golang:getmissingtools (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-html, v0.3.0
autocomplete-plus, v2.4.1
autocomplete-plus-async, v0.22.0
go-plus, v3.2.3
linter, v0.12.0
linter-golint, v0.2.0

# Dev
No dev packages
```

**Comment by iam4x** [comment]
Hello @jacobsantos 

It seems more like an https://github.com/yoshiori/linter-golint issue, do you mind reporting this repo?

Thank's
