### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/alexhawkins/.atom/packages/linter-jsxhint/node_modules/.bin'

### ISSUE THREAD

**Issue by alexhawkins** [AtomLinter/Linter#464]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/alexhawkins/.atom/packages/linter-jsxhint/node_modules/.bin'

```
At fs.js:807

Error: ENOENT, no such file or directory '/Users/alexhawkins/.atom/packages/linter-jsxhint/node_modules/.bin'
  at Error (native)
  at fs.statSync (fs.js:807:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterJsxhint.Linter._cachedStatSync (/Users/alexhawkins/.atom/packages/linter/lib/linter.coffee:69:17)
  at LinterJsxhint.Linter.getCmdAndArgs (/Users/alexhawkins/.atom/packages/linter/lib/linter.coffee:86:16)
  at LinterJsxhint.Linter.lintFile (/Users/alexhawkins/.atom/packages/linter/lib/linter.coffee:127:24)
  at /Users/alexhawkins/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /Users/alexhawkins/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -0:57.7 core:save (atom-text-editor.editor.is-focused)
     -0:52.6 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:49.1 core:move-down (atom-text-editor.editor.mini)
     -0:47.8 core:confirm (atom-text-editor.editor.mini)
     -0:44.2 core:save (atom-text-editor.editor.is-focused)
     -0:34.4 core:undo (atom-text-editor.editor.is-focused)
     -0:29.1 editor:newline (atom-text-editor.editor.is-focused)
  9x -0:28.1 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.9 core:move-right (atom-text-editor.editor.is-focused)
     -0:24.6 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.4 editor:newline (atom-text-editor.editor.is-focused)
  5x -0:22.9 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:19.1 grammar-selector:show (atom-text-editor.editor.is-focused)
  6x -0:14.8 core:move-down (atom-text-editor.editor.mini)
     -0:13.1 core:confirm (atom-text-editor.editor.mini)
     -0:01.2 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "autocomplete"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
angularjs-styleguide-snippets, v0.5.0
atom-beautify, v0.21.4
atom-jsx-transform, v0.1.0
atom-ternjs, v0.5.4
autoclose-html, v0.15.0
autocomplete-css, v0.4.0
autocomplete-html, v0.3.0
autocomplete-plus, v2.4.2
autocomplete-snippets, v1.0.1
color-picker, v1.4.4
html-id-class-snippets, v1.4.1
html2haml, v0.6.0
jshint, v1.3.0
linter, v0.12.0
minimap, v4.5.0
monokai, v0.12.0
react, v0.9.11
script, v2.18.0

# Dev
No dev packages
```

**Comment by iam4x** [comment]
Try:

* `$ cd /Users/alexhawkins/.atom/packages/linter-jsxhint/`
* `$ apm install`
