### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by rhodul** [AtomLinter/Linter#466]
[Enter steps to reproduce below:]

1. Just start the editor.

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Failed to activate the linter package

```
At Cannot find module '/Users/asdf/.atom/packages/linter-jsl/lib/linter-jsl'

Error: Cannot find module '/Users/adsf/.atom/packages/linter-jsl/lib/linter-jsl'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at LinterInitializer.activate (/Users/asdf/.atom/packages/linter/lib/init.coffee:87:30)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.4.2
language-puppet, v0.10.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-jsl, v0.0.1
linter-php, v0.0.11
linter-puppet-lint, v0.2.8
linter-scss-lint, v0.0.14

# Dev
No dev packages
```

**Comment by iam4x** [comment]
Seems an error with linter-jsl

**Comment by rhodul** [comment]
Yes, README in /Users/asdf/.atom/packages/linter-jsl says it's unfinished.

**Comment by iam4x** [comment]
You should disable it or uninstall it until it's ready :)

**Comment by brunowego** [comment]
+
