### ISSUE TITLE
Failed to load a language-javascript package grammar

### ISSUE THREAD

**Issue by slava-viktorov** [AtomLinter/Linter#467]
[Enter steps to reproduce below:]

1. Open js file

**Atom Version**: 0.187.0-abf368e
**System**: linux 3.17.1-52.g5c4d099-desktop
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Failed to load a language-javascript package grammar

```
At Arguments to path.join must be strings in /usr/local/share/atom/resources/app/node_modules/language-javascript/grammars/javascript.json

TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:472:13)
  at new LinterFlow (/home/slava/.atom/packages/linter-flow/lib/linter-flow.coffee:106:40)
  at LinterView.initLinters (/home/slava/.atom/packages/linter/lib/linter-view.coffee:51:27)
  at /home/slava/.atom/packages/linter/lib/linter-view.coffee:103:8
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.handleGrammarChange (/usr/local/share/atom/resources/app/src/text-editor.js:2842:27)
  at /usr/local/share/atom/resources/app/src/text-editor.js:200:24
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/usr/local/share/atom/resources/app/src/tokenized-buffer.js:168:27)
  at TokenizedBuffer.module.exports.TokenizedBuffer.grammarAddedOrUpdated (/usr/local/share/atom/resources/app/src/tokenized-buffer.js:124:23)
  at /usr/local/share/atom/resources/app/src/tokenized-buffer.js:3:61
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (/usr/local/share/atom/resources/app/node_modules/first-mate/lib/grammar-registry.js:84:20)
  at Grammar.module.exports.Grammar.activate (/usr/local/share/atom/resources/app/node_modules/first-mate/lib/grammar.js:176:48)
  at /usr/local/share/atom/resources/app/src/package.js:511:25
  at /usr/local/share/atom/resources/app/node_modules/first-mate/lib/grammar-registry.js:129:55
  at parseContents (/usr/local/share/atom/resources/app/node_modules/season/lib/cson.js:95:47)
  at /usr/local/share/atom/resources/app/node_modules/season/lib/cson.js:183:20
  at fs.js:337:14
  at FSReqWrap.oncomplete (fs.js:100:15)

  at /usr/local/share/atom/resources/app/node_modules/language-javascript/grammars/javascript.json:1:1
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "Remote-FTP",
      "remote-edit",
      "remote-sync",
      "SFTP-deployment",
      "language-javascript-subtlegradient",
      "atom-jshint",
      "selection-outlines"
    ]
  },
  "linter": {
    "statusBar": "Show error of the selected line",
    "showInfoMessages": true,
    "lintDebug": true
  }
}
```

### Installed Packages

```coffee
# User
atom-deconsole, v0.0.1
atom-ternjs, v0.5.5
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.2
autocomplete-plus-async, v0.22.0
autocomplete-snippets, v1.0.1
coffee-navigator, v0.0.16
emmet, v2.3.4
file-icons, v1.5.1
foundation5-snippets, v0.2.0
gulp-snippets, v0.6.1
javascript-snippets, v1.0.0
js-refactor, v0.3.0
jsformat, v0.7.18
jshint, v1.3.0
language-javascript-semantic, v0.1.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-eslint, v0.4.2
linter-flow, v0.1.3
linter-haml, v0.1.1
linter-jscs, v1.9.0
linter-jshint, v0.1.0
linter-jsonlint, v0.1.2
linter-php, v0.0.11
linter-scss-lint, v0.0.14
linter-xmllint, v0.0.5
pretty-json, v0.3.2
refactor, v0.4.1
remote-atom, v1.2.0
script, v2.18.0
symbols-tree-view, v0.6.1
webbox-color, v0.5.6

# Dev
No dev packages
```

**Comment by hd-deman** [comment]
Слава, это проблема пакета [linter-flow](https://github.com/AtomLinter/linter-flow)

**Comment by hd-deman** [comment]
@paulcbetts just want you to know ::)

**Comment by paulcbetts** [comment]
@hd-deman Я не могу говорить по-русски очень хорошо, но я думаю, что это проблема исправлена в последней версии. :)
