### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory 'C:\Users\HaravyV\AppData\Local\atom\app-0.187.0\rustc'

### ISSUE THREAD

**Issue by VHaravy** [AtomLinter/Linter#475]
1. Open any Rust file.

**Atom Version**: 0.187.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory 'C:\Users\HaravyV\AppData\Local\atom\app-0.187.0\rustc'

```
At fs.js:807

Error: ENOENT, no such file or directory 'C:\Users\HaravyV\AppData\Local\atom\app-0.187.0\rustc'
  at Error (native)
  at fs.statSync (fs.js:807:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterRust.Linter._cachedStatSync (C:\Users\HaravyV\.atom\packages\linter\lib\linter.coffee:69:17)
  at LinterRust.Linter.getCmdAndArgs (C:\Users\HaravyV\.atom\packages\linter\lib\linter.coffee:86:16)
  at LinterRust.Linter.lintFile (C:\Users\HaravyV\.atom\packages\linter\lib\linter.coffee:127:24)
  at LinterRust.lintFile (C:\Users\HaravyV\.atom\packages\linter-rust\lib\linter-rust.coffee:42:7)
  at LinterRust.lintFile (C:\Users\HaravyV\.atom\packages\linter-rust\lib\linter-rust.coffee:1:1)
  at C:\Users\HaravyV\.atom\packages\linter\lib\linter-view.coffee:158:18
  at Array.forEach (native)
  at C:\Users\HaravyV\.atom\packages\linter\lib\linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
  2x -1:45.3 core:backspace (atom-text-editor.editor.mini)
     -1:43.7 core:confirm (atom-text-editor.editor.mini)
     -0:32.3 pane:reopen-closed-item (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
language-rust, v0.4.2
linter, v0.12.0
linter-rust, v0.0.6

# Dev
No dev packages
```

**Comment by VHaravy** [comment]
After upgrading `linter-rust` to 0.0.7 this is no longer reproducing.
