### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by netmou** [AtomLinter/Linter#477]
Cannot read property 'split' of undefined
Hide Stack Trace
TypeError: Cannot read property 'split' of undefined
    at findFile (C:\Users\Administrator\.atom\packages\linter\lib\util.coffee:19:21)
    at LinterHtmlhint.setupHtmlHintRc (C:\Users\Administrator\.atom\packages\linter-htmlhint\lib\linter-htmlhint.coffee:30:16)
    at C:\Users\Administrator\.atom\packages\linter-htmlhint\lib\linter-htmlhint.coffee:3:61
    at Config.module.exports.Config.observeKeyPath (D:\Atom\resources\app\src\config.js:612:7)
    at Config.module.exports.Config.observe (D:\Atom\resources\app\src\config.js:126:21)
    at new LinterHtmlhint (C:\Users\Administrator\.atom\packages\linter-htmlhint\lib\linter-htmlhint.coffee:41:19)
    at LinterView.initLinters (C:\Users\Administrator\.atom\packages\linter\lib\linter-view.coffee:64:43)
    at new LinterView (C:\Users\Administrator\.atom\packages\linter\lib\linter-view.coffee:45:12)
    at C:\Users\Administrator\.atom\packages\linter\lib\init.coffee:104:24
    at Workspace.module.exports.Workspace.observeTextEditors (D:\Atom\resources\app\src\workspace.js:282:9)

**Comment by netmou** [comment]
when i open a php file by the shortcut 'ctl+t'

**Comment by brunowego** [comment]
+1

**Comment by d4k0** [comment]
Try this change (it will be in the next version of linter-htmlhint): https://github.com/basarat/linter-htmlhint/commit/5dcdd39656b9ec1225334c8556a2903b82a1a8ce

**Comment by tumri** [comment]
I'm getting this error whenever I try to activate Linter.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'C:\Users\Tumri\.atom\packages\linter-lintr/lib/linter-lintr'

Error: Cannot find module 'C:\Users\Tumri\.atom\packages\linter-lintr/lib/linter-lintr'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at LinterInitializer.activate (C:\Users\Tumri\.atom\packages\linter\lib\init.coffee:73:28)
  at Package.module.exports.Package.activateNow (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:225:19)
  at C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:206:30
  at Package.module.exports.Package.measure (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:152:15)
  at Package.module.exports.Package.activate (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:199:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\package-manager.js:435:21)
  at C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\package-manager.js:304:19
  at C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\config.js:563:20
  at Emitter.module.exports.Emitter.emit (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\config.js:725:29)
  at Config.module.exports.Config.setRawValue (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\config.js:540:19)
  at Config.module.exports.Config.set (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\config.js:224:14)
  at Config.module.exports.Config.removeAtKeyPath (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\config.js:334:12)
  at Package.module.exports.Package.enable (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:137:26)
  at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\src\package-manager.js:132:14)
  at HTMLButtonElement.<anonymous> (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\node_modules\settings-view\lib\package-card.js:209:27)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (C:\Users\Tumri\AppData\Local\atom\app-0.190.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
     -9:45.9 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -9:13.2 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {},
  "linter": {
    "showInfoMessages": true
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.6.0
linter, v0.12.0
linter-bootlint, v0.0.5
linter-clang, v2.25.1
linter-csslint, v0.0.11
linter-flexpmd, v0.1.9
linter-haml, v0.1.1
linter-hlint, v0.3.1
linter-htmlhint, v0.0.12
linter-javac, v0.1.3
linter-js-yaml, v1.0.0
linter-jscs, v1.10.0
linter-jshint, v0.1.2
linter-jsxhint, v0.1.1
linter-less, v0.3.1
linter-lintr, v0.0.1
linter-lua, v0.1.5
linter-php, v0.0.12
linter-phpcs, v0.0.12
linter-phpmd, v0.0.10
linter-pylint, v0.2.1
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
linter-rust, v0.0.8
linter-scalac, v0.3.3
linter-scspell, v1.1.1
linter-scss-lint, v0.0.14
linter-shellcheck, v0.0.7
linter-stylint, v0.4.0
linter-tidy, v1.0.0
linter-tslint, v0.2.1
linter-xmllint, v0.0.5
minimap, v4.7.6
save-session, v0.13.1

# Dev
No dev packages
```
