### ISSUE TITLE
Failed to load a language-html package grammar

### ISSUE THREAD

**Issue by d4k0** [AtomLinter/Linter#480]
[Enter steps to reproduce below:]

This happens when I want to open some HTML file. This error first occured when I updated to Atom 0.188.0 (from 0.186.0) today. However, this error also seems to occur with other file types as can be seen here: https://github.com/AtomLinter/Linter/issues/477

**Atom Version**: 0.188.0
**System**: *REMOVED*
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Failed to load a language-html package grammar

```
At Cannot read property 'split' of undefined in D:\Programme\Dokumente\Atom\resources\app\node_modules\language-html\grammars\html.json

TypeError: Cannot read property 'split' of undefined
  at findFile (C:\Users\MyName\.atom\packages\linter\lib\util.coffee:16:19)
  at LinterHtmlhint.setupHtmlHintRc (C:\Users\MyName\.atom\packages\linter-htmlhint\lib\linter-htmlhint.coffee:26:14)
  at C:\Users\MyName\.atom\packages\linter-htmlhint\lib\linter-htmlhint.coffee:1:1
  at Config.module.exports.Config.observeKeyPath (D:\Programme\Dokumente\Atom\resources\app\src\config.js:612:7)
  at Config.module.exports.Config.observe (D:\Programme\Dokumente\Atom\resources\app\src\config.js:126:21)
  at new LinterHtmlhint (C:\Users\MyName\.atom\packages\linter-htmlhint\lib\linter-htmlhint.coffee:36:17)
  at LinterView.initLinters (C:\Users\MyName\.atom\packages\linter\lib\linter-view.coffee:51:27)
  at C:\Users\MyName\.atom\packages\linter\lib\linter-view.coffee:103:8
  at Emitter.module.exports.Emitter.emit (D:\Programme\Dokumente\Atom\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.handleGrammarChange (D:\Programme\Dokumente\Atom\resources\app\src\text-editor.js:2809:27)
  at D:\Programme\Dokumente\Atom\resources\app\src\text-editor.js:200:24
  at Emitter.module.exports.Emitter.emit (D:\Programme\Dokumente\Atom\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (D:\Programme\Dokumente\Atom\resources\app\src\tokenized-buffer.js:168:27)
  at TokenizedBuffer.module.exports.TokenizedBuffer.grammarAddedOrUpdated (D:\Programme\Dokumente\Atom\resources\app\src\tokenized-buffer.js:124:23)
  at D:\Programme\Dokumente\Atom\resources\app\src\tokenized-buffer.js:3:61
  at Emitter.module.exports.Emitter.emit (D:\Programme\Dokumente\Atom\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (D:\Programme\Dokumente\Atom\resources\app\node_modules\first-mate\lib\grammar-registry.js:84:20)
  at Grammar.module.exports.Grammar.activate (D:\Programme\Dokumente\Atom\resources\app\node_modules\first-mate\lib\grammar.js:176:48)
  at D:\Programme\Dokumente\Atom\resources\app\src\package.js:517:25
  at D:\Programme\Dokumente\Atom\resources\app\node_modules\first-mate\lib\grammar-registry.js:129:55
  at parseContents (D:\Programme\Dokumente\Atom\resources\app\node_modules\season\lib\cson.js:95:47)
  at D:\Programme\Dokumente\Atom\resources\app\node_modules\season\lib\cson.js:183:20
  at fs.js:337:14
  at FSReqWrap.oncomplete (fs.js:100:15)

  at D:\Programme\Dokumente\Atom\resources\app\node_modules\language-html\grammars\html.json:1:1
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-monokai"
    ]
  },
  "linter": {
    "statusBar": "Show all errors",
    "showInfoMessages": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.5.6
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.6.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-htmlhint, v0.0.9
linter-jshint, v0.1.0
linter-tidy, v1.0.0
open-last-project, v0.3.5
project-manager, v1.15.5
seti-monokai, v0.3.1
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by d4k0** [comment]
Seems to be fixed by applying the changes from https://github.com/basarat/linter-htmlhint/commit/5dcdd39656b9ec1225334c8556a2903b82a1a8ce (this will be in the next version of linter-htmlhint).
