### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/Scott/.rvm/gems/ruby-2.1.2/bin/rubocop'

### ISSUE THREAD

**Issue by scottyschup** [AtomLinter/Linter#485]
[Enter steps to reproduce below:]

1. I just opened atom from iTerm with `atom .`

**Atom Version**: 0.188.0
**System**: Mac OS X 10.9.5
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/Scott/.rvm/gems/ruby-2.1.2/bin/rubocop'

```
At fs.js:807

Error: ENOENT, no such file or directory '/Users/Scott/.rvm/gems/ruby-2.1.2/bin/rubocop'
  at Error (native)
  at fs.statSync (fs.js:807:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterRubocop.Linter._cachedStatSync (/Users/Scott/.atom/packages/linter/lib/linter.coffee:69:17)
  at LinterRubocop.Linter.getCmdAndArgs (/Users/Scott/.atom/packages/linter/lib/linter.coffee:86:16)
  at LinterRubocop.Linter.lintFile (/Users/Scott/.atom/packages/linter/lib/linter.coffee:127:24)
  at /Users/Scott/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /Users/Scott/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -1:14.4 settings-view:open (atom-text-editor.editor.is-focused)
     -0:00.4 core:close (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "autocomplete-plus",
      "atom-jshint",
      "jshint",
      "atom-lint"
    ]
  },
  "linter": {
    "showHighlighting": false,
    "lintOnChange": false
  }
}
```

### Installed Packages

```coffee
# User
emmet-atom, v2.3.4
linter, v0.12.0
linter-csslint, v0.0.11
linter-erb, v0.1.0
linter-jshint, v0.1.0
linter-rubocop, v0.2.2
linter-scss-lint, v0.0.14

# Dev
No dev packages
```

**Comment by scottyschup** [comment]
This has come up a few times now. Usually I just have to go in and and change my PATH back to `/Users/Scott/.rbenv/versions/2.1.2/bin/rubocop`. I'm not sure what is changing it in the first place though. Updates perhaps?

**Comment by PiotrCzapla** [comment]
Similar issue was recently fixed in Atom-linter: https://github.com/yujinakayama/atom-lint/issues/30

**Comment by scottyschup** [comment]
It was happening once every week or two for a while but hasn't occurred in over a month, so I'm thinking it was resolved. Thanks!

**Comment by scottyschup** [comment]
And now it's back. And changing the rubocop path and restarting atom is no longer fixing it. Though the error message is slightly different this time: 

Uncaught Error: ENOENT: no such file or directory, stat '/Users/Scott/.rbenv/versions/2.1.2/bin/rubocop '
fs.js:846
Hide Stack Trace
Error: ENOENT: no such file or directory, stat '/Users/Scott/.rbenv/versions/2.1.2/bin/rubocop
'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterRubocop.Linter._cachedStatSync (/Users/Scott/.atom/packages/linter/lib/linter.coffee:87:17)
  at LinterRubocop.Linter.getCmdAndArgs (/Users/Scott/.atom/packages/linter/lib/linter.coffee:104:16)
  at LinterRubocop.Linter.lintFile (/Users/Scott/.atom/packages/linter/lib/linter.coffee:145:24)
  at /Users/Scott/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/Scott/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

This time I was eventually able to get around it by removing "rubocop" from the end of the path.
