### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'undefined'

### ISSUE THREAD

**Issue by jacobfike** [AtomLinter/Linter#493]
This happens at startup in API 1.0 preview mode

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'undefined'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat 'undefined'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterJshint.Linter._cachedStatSync (/Users/jfike/.atom/packages/linter/lib/linter.coffee:69:17)
  at LinterJshint.Linter.getCmdAndArgs (/Users/jfike/.atom/packages/linter/lib/linter.coffee:86:16)
  at LinterJshint.Linter.lintFile (/Users/jfike/.atom/packages/linter/lib/linter.coffee:127:24)
  at /Users/jfike/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /Users/jfike/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      "Thumbs.db",
      ".DS_Store",
      "target",
      "build"
    ],
    "disabledPackages": [
      "term2",
      "atom-jsfmt",
      "linter-jscs",
      "minimap-color-highlight",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "minimap",
      "themed-settings",
      "autocomplete-plus-async",
      "Tern",
      "docblockr",
      "duplicate-and-comment",
      "fancy-new-file",
      "task-list",
      "file-types",
      "language-javascript-semantic",
      "script"
    ],
    "themes": [
      "dark-flat-ui",
      "electron-dark-syntax"
    ],
    "projectHome": "/Users/jfike/workspace"
  },
  "linter": {
    "lintOnSave": false,
    "showErrorInline": false,
    "statusBar": "Show error of the selected line"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-ternjs, v0.5.19
autocomplete-plus, v2.9.0
dark-flat-ui, v1.1.3
editorconfig, v0.3.3
electron-dark-syntax, v1.0.1
file-icons, v1.5.3
highlight-selected, v0.9.1
jsonpp, v0.0.6
language-csharp, v0.5.0
language-ejs, v0.1.0
language-ini, v1.10.0
linter, v0.12.0
linter-jshint, v0.1.1
merge-conflicts, v1.2.10
project-manager, v1.15.5
set-syntax, v0.2.1

# Dev
No dev packages
```

**Comment by diegoconcha** [comment]
:+1: I have the same issue on osx with atom 0.194.0

**Comment by koalalorenzo** [comment]
Same issue here!

**Comment by jbergstroem** [comment]
Just reproduced too (while testing with `atom --one`)

**Comment by leofle** [comment]
same with 0.196.0

**Comment by pchelnikov** [comment]
+ 0.196.0

**Comment by kerrishotts** [comment]
Seems to be the linter-jshint plugin. If you uninstall it (don't just disable it!), the error goes away (assuming you don't use it, or can use another javascript linter like eslint)
