### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node' thrown from status-bar

### ISSUE THREAD

**Issue by mik01aj** [AtomLinter/Linter#503]
### How to reproduce:

1. Install linter (with no linter-* packages)
2. Focus any js editor and get the exception
3. Go to settings, disable linter
4. Focus any js editor again and observe there is no exception

**Atom Version**: 0.191.0
**System**: Mac OS X 10.10.2
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v0.68.0

### Stack Trace

Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/status-bar-view.js:97

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
  at Error (native)
  at status-bar.StatusBarView.addRightTile (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/status-bar-view.js:97:23)
  at StatusBarSummaryView.render (/Users/mikolajdadela/.atom/packages/linter/lib/statusbar-summary-view.coffee:28:23)
  at LinterView.updateViews (/Users/mikolajdadela/.atom/packages/linter/lib/linter-view.coffee:229:27)
  at LinterView.display (/Users/mikolajdadela/.atom/packages/linter/lib/linter-view.coffee:225:6)
  at LinterView.processMessage (/Users/mikolajdadela/.atom/packages/linter/lib/linter-view.coffee:173:8)
  at LinterView.processMessage (/Users/mikolajdadela/.atom/packages/linter/lib/linter-view.coffee:1:1)
  at /Users/mikolajdadela/.atom/packages/linter/lib/linter-view.coffee:159:14
  at LinterJscs.Linter.processMessage (/Users/mikolajdadela/.atom/packages/linter/lib/linter.coffee:181:5)
  at /Users/mikolajdadela/.atom/packages/linter/lib/linter.coffee:155:8
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -8:11.0 core:cancel (input#linter.showInfoMessages)
     -7:21.0 core:save (atom-text-editor.editor)
     -7:19.6 pane:show-previous-item (atom-text-editor.editor)
     -7:14.9 core:save (atom-text-editor.editor)
  2x -4:32.8 core:backspace (atom-text-editor.editor.mini)
     -4:32.4 core:confirm (atom-text-editor.editor.mini)
  5x -2:59.9 core:backspace (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "linter-eslint",
      "linter-pylint",
      "linter-jshint",
      "linter-jsxhint",
      "linter-jscs"
    ],
    "themes": [
      "isotope-light-ui",
      "seti-syntax"
    ],
    "projectHome": "~/code/"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
color-picker, v1.6.0
file-type-icons, v0.5.4
isotope-light-ui, v2.0.2
language-groovy, v0.4.0
language-javascript-semantic, v0.1.0
linter, v0.12.0
minimap, v4.7.6
open-last-project, v0.4.1
pretty-json, v0.3.3
react, v0.11.4
refactor, v0.4.1
seti-syntax, v0.3.3
sync-settings, v0.2.2

# Dev
No dev packages
```

Reported also as https://github.com/atom/status-bar/issues/49

**Comment by mik01aj** [comment]
Now what's really interesting... I re-enabled deprecation cop, restarted Atom and I don't get the exception anymore.
