### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'C:\usr\local\bin\stylint'

### ISSUE THREAD

**Issue by rootasjey** [AtomLinter/Linter#505]
Hello, the package isn't working on Windows 8.1 with Atom 0.192.
Maybe it's related to the OS : the directory that _linter-stylint_ wants to find seems to be a unix one.

[steps to reproduce below:]

1. Install [linter](https://github.com/AtomLinter/Linter) and [linter-stylint](https://atom.io/packages/linter-stylint)
2. Open a .styl file

**Atom Version**: 0.192.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\usr\local\bin\stylint'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat 'C:\usr\local\bin\stylint'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterStylint.Linter._cachedStatSync (C:\Users\Jeremie\.atom\packages\linter\lib\linter.coffee:69:17)
  at LinterStylint.Linter.getCmdAndArgs (C:\Users\Jeremie\.atom\packages\linter\lib\linter.coffee:86:16)
  at LinterStylint.Linter.lintFile (C:\Users\Jeremie\.atom\packages\linter\lib\linter.coffee:127:24)
  at C:\Users\Jeremie\.atom\packages\linter\lib\linter-view.coffee:158:18
  at Array.forEach (native)
  at C:\Users\Jeremie\.atom\packages\linter\lib\linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "save-session",
      "linter-jsxhint"
    ],
    "autoHideMenuBar": true
  },
  "linter": {
    "statusBar": "Show all errors",
    "showInfoMessages": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.1.0
atom-ternjs, v0.5.19
autocomplete-css, v0.6.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.10.0
autocomplete-snippets, v1.2.0
autohide-tree-view, v0.16.5
color-picker, v1.6.0
file-icons, v1.5.4
highlight-selected, v0.9.1
linter, v0.12.0
linter-jshint, v0.1.2
linter-stylint, v0.5.0
minimap, v4.7.6
react, v0.11.4
script, v2.19.0
Stylus, v0.7.0

# Dev
No dev packages
```

**Comment by steveoh** [comment]
:+1:

**Comment by terrycloth** [comment]
I'm getting basically the same thing on Ubuntu 15.04 (x64).

* Atom 0.205.0 (installed from the [WebUpD8 Team's PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/atom))
* Linter 0.12.6

> Uncaught Error: ENOENT: no such file or directory, stat '/usr/local/bin/stylint'

Stack Trace: 

```
fs.js:846

Error: ENOENT: no such file or directory, stat '/usr/local/bin/stylint'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterStylint.Linter._cachedStatSync ($HOME/.atom/packages/linter/lib/linter.coffee:87:17)
  at LinterStylint.Linter.getCmdAndArgs ($HOME/.atom/packages/linter/lib/linter.coffee:104:16)
  at LinterStylint.Linter.lintFile ($HOME/.atom/packages/linter/lib/linter.coffee:145:24)
  at $HOME/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at $HOME/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by steveoh** [comment]
I'm not sure how to install plugins locally but I wonder if something [like this](https://github.com/AtomLinter/linter-stylint/pull/10) will help this along. Seems like the linter has no idea where the executable is.
