### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/urs/bin/pep8'

### ISSUE THREAD

**Issue by rogerfc** [AtomLinter/Linter#506]
[Enter steps to reproduce below:]

1. Install Atom + linter + linter-pep8 packages
2. Open any .py file

**Atom Version**: 0.192.0
**System**: linux 3.13.0-49-generic
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/urs/bin/pep8'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat '/urs/bin/pep8'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at Pep8Linter.Linter._cachedStatSync (/home/rfirpo/.atom/packages/linter/lib/linter.coffee:69:17)
  at Pep8Linter.Linter.getCmdAndArgs (/home/rfirpo/.atom/packages/linter/lib/linter.coffee:86:16)
  at Pep8Linter.Linter.lintFile (/home/rfirpo/.atom/packages/linter/lib/linter.coffee:127:24)
  at /home/rfirpo/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /home/rfirpo/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:10.8 tree-view:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".DS_Store",
      "Thumbs.db"
    ],
    "projectHome": "/home/rfirpo/car/jobboard"
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
django-templates, v0.4.0
language-mako, v0.4.0
linter, v0.12.0
linter-pep8, v0.1.0
linter-python-pep8, v0.2.0
markdown-format, v2.5.0
open-last-project, v0.4.1

# Dev
No dev packages
```

**Comment by rogerfc** [comment]
This is clearly a typo in the resolution of the pep8 path.
Note that this is independent of the "Pep8 Executable Path" setting in the linter-pep8 package.

**Comment by rogerfc** [comment]
Sorry, it was due to a bad configuration setting from another package (linter-python-pep8)
