### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'hlint'

### ISSUE THREAD

**Issue by greentornado** [AtomLinter/Linter#507]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'hlint'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat 'hlint'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterHLint.Linter._cachedStatSync (/Users/Hai/.atom/packages/linter/lib/linter.coffee:69:17)
  at LinterHLint.Linter.getCmdAndArgs (/Users/Hai/.atom/packages/linter/lib/linter.coffee:86:16)
  at LinterHLint.Linter.lintFile (/Users/Hai/.atom/packages/linter/lib/linter.coffee:127:24)
  at /Users/Hai/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/Hai/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v1.7.0
editor-stats, v0.17.0
ide-haskell, v0.3.6
jsformat, v0.8.0
language-haskell, v1.0.0
linter, v0.12.1
linter-hlint, v0.3.1
minimap, v4.7.6
monokai, v0.14.0

# Dev
No dev packages
```

**Comment by iam4x** [comment]
Issue with `linter-hlint` post the issue: https://github.com/AtomLinter/linter-hlint
