### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/usr/local/bin/stylint'

### ISSUE THREAD

**Issue by ymatuhin** [AtomLinter/Linter#513]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/usr/local/bin/stylint'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat '/usr/local/bin/stylint'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterStylint.Linter._cachedStatSync (/Users/ymatuhin/.atom/packages/linter/lib/linter.coffee:69:17)
  at LinterStylint.Linter.getCmdAndArgs (/Users/ymatuhin/.atom/packages/linter/lib/linter.coffee:86:16)
  at LinterStylint.Linter.lintFile (/Users/ymatuhin/.atom/packages/linter/lib/linter.coffee:127:24)
  at /Users/ymatuhin/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/ymatuhin/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
  2x -7:33 core:paste (atom-text-editor.editor)
     -7:28.5.0 core:backspace (atom-text-editor.editor)
     -7:26.9.0 autocomplete-plus:cancel (atom-text-editor.editor)
     -7:25.8.0 core:save (atom-text-editor.editor)
     -7:24.2.0 core:copy (atom-text-editor.editor)
     -7:23.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
  2x -7:21.2.0 core:move-down (atom-text-editor.editor.mini)
     -7:20.8.0 core:confirm (atom-text-editor.editor.mini)
     -7:18.3.0 core:paste (atom-text-editor.editor)
     -7:17.9.0 core:save (atom-text-editor.editor)
  2x -7:10.7.0 core:copy (atom-text-editor.editor)
     -0:16.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:15.1.0 core:move-down (atom-text-editor.editor.mini)
     -0:14.8.0 core:confirm (atom-text-editor.editor.mini)
     -0:05.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:03.3.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "code-links",
      "linter-tidy",
      "linter-coffeelint"
    ]
  },
  "linter": {
    "ignoredLinterErrors": [
      "jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
angularjs, v0.2.0
atom-beautify, v0.24.1
autocomplete-plus, v2.12.0
color-picker, v1.7.0
emmet, v2.3.8
file-icons, v1.5.4
linter, v0.12.1
linter-jshint, v0.1.2
linter-stylint, v0.5.0
minimap, v4.7.6
project-manager, v1.15.5
project-palette-finder, v2.4.17

# Dev
No dev packages
```

**Comment by ruslanchek** [comment]
Same case.

**Comment by johnantoni** [comment]
Same here

**Comment by corysimmons** [comment]
You need `stylint` available in terminal.

`npm i -g stylint`

**Comment by johnantoni** [comment]
thanks

**Comment by ymatuhin** [comment]
@corysimmons thanks

**Comment by corysimmons** [comment]
No problem. I'm having the problem where I can't get stylint to return any errors. I can pass it the most messed up code and it doesn't throw any warnings.

When I run `stylint foo.styl -s` (strict flag) it does throw warnings.

**Comment by rossPatton** [comment]
Hey @corysimmons cory, the actual defaults settings are verrrrrrry loose. You might want to try setting up a .stylintrc in your project dir.

https://github.com/rossPatton/stylint
