### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\timmy.ohman\AppData\Local\atom\app-0.198.0\¨g'

### ISSUE THREAD

**Issue by Riddarn97** [AtomLinter/Linter#530]
[Enter steps to reproduce below:]

1. Install Linter and Linter-cpplint
2. Open upp a .cpp file.

**Atom Version**: 0.198.0
**System**: Unknown Windows Version
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\timmy.ohman\AppData\Local\atom\app-0.198.0\¨g'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat 'C:\Users\timmy.ohman\AppData\Local\atom\app-0.198.0\¨g'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterCpplint.Linter._cachedStatSync (C:\Users\timmy.ohman\.atom\packages\linter\lib\linter.coffee:69:17)
  at LinterCpplint.Linter.getCmdAndArgs (C:\Users\timmy.ohman\.atom\packages\linter\lib\linter.coffee:86:16)
  at LinterCpplint.Linter.lintFile (C:\Users\timmy.ohman\.atom\packages\linter\lib\linter.coffee:127:24)
  at C:\Users\timmy.ohman\.atom\packages\linter\lib\linter-view.coffee:163:18
  at Array.forEach (native)
  at C:\Users\timmy.ohman\.atom\packages\linter\lib\linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:14.2.0 application:open-file (atom-text-editor.editor.is-focused)
  2x -0:09.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "C:\\Users\\timmy.ohman\\Projects"
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.14.2
language-batch, v0.3.3
linter, v0.12.2
linter-cpplint, v0.1.4
minimap, v4.8.0

# Dev
No dev packages
```

**Comment by Riddarn97** [comment]
I found the problem. I was just silly.
