### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\Admin\AppData\Local\atom\app-0.201.0\undefined'

### ISSUE THREAD

**Issue by eXon** [AtomLinter/Linter#545]
I updated the package and everytime I type, I keep getting this error.

1. Created a new file
2. Start typing
3. This error keep poping.

I use the eslint with the jsx plugin.

**Atom Version**: 0.201.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.6

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\Admin\AppData\Local\atom\app-0.201.0\undefined'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat 'C:\Users\Admin\AppData\Local\atom\app-0.201.0\undefined'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterJshint.Linter._cachedStatSync (C:\Users\Admin\.atom\packages\linter\lib\linter.coffee:70:5)
  at LinterJshint.Linter.getCmdAndArgs (C:\Users\Admin\.atom\packages\linter\lib\linter.coffee:16:3)
  at LinterJshint.Linter.lintFile (C:\Users\Admin\.atom\packages\linter\lib\linter.coffee:119:7)
  at LinterJshint.lintFile (C:\Users\Admin\.atom\packages\linter-jshint\lib\linter-jshint.coffee:56:5)
  at C:\Users\Admin\.atom\packages\linter\lib\linter-view.coffee:163:18
  at Array.forEach (native)
  at C:\Users\Admin\.atom\packages\linter\lib\linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -2:47.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:49.5.0 core:close (div.settings-view.pane-item)
  2x -1:27.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-babel",
      "linter-jshint",
      "linter-jsxhint",
      "refactor",
      "js-refactor",
      "language-mustache",
      "autosave"
    ],
    "destroyEmptyPanes": false
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.10
linter, v0.12.6
linter-eslint, v0.5.8
npm-autocomplete, v0.1.2
react, v0.11.8

# Dev
No dev packages
```

**Comment by iam4x** [comment]
It's weird it tells that the error comes from `LinterJshint` try to remove it or disable.

**Comment by eXon** [comment]
Seems to work fine with JSHint disabled. Weird.
