### ISSUE TITLE
Uncaught TypeError: Invalid Point: (12, NaN)

### ISSUE THREAD

**Issue by Yajo** [AtomLinter/Linter#570]
[Enter steps to reproduce below:]

1. Edit an XML file.
2. It raises many times while writing, so I don't know what raises it.

**Atom Version**: 0.210.0
**System**: "Fedora release
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.7

### Stack Trace

Uncaught TypeError: Invalid Point: (12, NaN)

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:65

TypeError: Invalid Point: (12, NaN)
  at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:956:13)
  at TextBuffer.module.exports.TextBuffer.clipRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:944:20)
  at TextBuffer.module.exports.TextBuffer.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:674:46)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/usr/share/atom/resources/app.asar/src/display-buffer.js:1383:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:1269:59)
  at LinterView.createMarker (/home/jllopis/.atom/packages/linter/lib/linter-view.coffee:190:22)
  at LinterView.display (/home/jllopis/.atom/packages/linter/lib/linter-view.coffee:227:17)
  at LinterView.processMessage (/home/jllopis/.atom/packages/linter/lib/linter-view.coffee:178:8)
  at LinterView.processMessage (/home/jllopis/.atom/packages/linter/lib/linter-view.coffee:1:1)
  at /home/jllopis/.atom/packages/linter/lib/linter-view.coffee:164:14
  at LinterXmllint.Linter.processMessage (/home/jllopis/.atom/packages/linter/lib/linter.coffee:241:5)
  at /home/jllopis/.atom/packages/linter/lib/linter.coffee:173:8
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -2:34.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:32.4.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -2:31.5.0 core:cut (atom-text-editor.editor.is-focused)
     -2:31.2.0 core:delete (atom-text-editor.editor.is-focused)
     -2:30.7.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -2:30.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:29.8.0 core:paste (atom-text-editor.editor.is-focused)
     -2:28.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:22.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -1:57.5.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:36.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:32.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:31.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:16.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.8.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  },
  "linter": {
    "subtleLinterErrors": [
      "xmllint",
      "flake8"
    ],
    "ignoredLinterErrors": [
      "php"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.0.0
language-docker, v1.1.3
language-restructuredtext, v0.6.0
linter, v0.12.7
linter-flake8, v1.4.2
linter-php, v0.0.15
linter-xmllint, v0.0.6
minimap, v4.10.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
rst-preview-pandoc, v0.1.9

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
You might want to report this in `linter-xmllint`.
