### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by mrextreme** [AtomLinter/Linter#572]
TL;DR: Solution
============
[by Linter Team]
Reload atom with `View > Reload`

This problem is probably going to happen to everyone as you upgrade. We're sorry, but we couldn't test the upgrade process and were unable to predict this problem.

Original report
===========

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v1.0.0

### Stack Trace

Uncaught Error: Cannot find module 'lodash'

```
At module.js:330

Error: Cannot find module 'lodash'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at LinterJshint.Linter.getEditorScopesForPosition (/Users/roland/.atom/packages/linter/lib/linter.coffee:291:31)
  at LinterJshint.Linter.computeRange (/Users/roland/.atom/packages/linter/lib/linter.coffee:337:5)
  at LinterJshint.Linter.createMessage (/Users/roland/.atom/packages/linter/lib/linter.coffee:16:3)
  at LinterJshint.<anonymous> (/Users/roland/.atom/packages/linter/lib/linter.coffee:235:37)
  at Function.self.forEach (/Users/roland/.atom/packages/linter/node_modules/xregexp/xregexp-all.js:542:22)
  at LinterJshint.Linter.processMessage (/Users/roland/.atom/packages/linter/lib/linter.coffee:236:7)
  at /Users/roland/.atom/packages/linter/lib/linter.coffee:165:7
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
  2x -1:35.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:34.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:34.4.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
 16x -1:34.2.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:32.1.0 core:copy (atom-text-editor.editor.is-focused)
     -1:31.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:31.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:31.4.0 core:paste (atom-text-editor.editor.is-focused)
     -1:31 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:28.4.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:26.3.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:25.2.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:03.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:03.0 core:move-right (atom-text-editor.editor.is-focused)
  7x -0:02.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autoflow",
      "autocomplete",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-java",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "metrics",
      "spell-check",
      "linter-csslint"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "audioBeep": false
  },
  "linter": {
    "lintOnChange": false,
    "lintOnEditorFocus": false,
    "showHighlighting": false,
    "showGutters": false,
    "showErrorInline": true,
    "statusBar": "Show all errors"
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v2.0.0
autocomplete-paths, v1.0.2
highlight-line, v0.11.0
highlight-selected, v0.10.1
keyboard-localization, v1.4.3
language-css-plus, v0.3.0
language-php, v0.26.0
language-smarty-php, v0.5.0
linter, v1.0.0
linter-jshint, v0.1.6
linter-php, v0.0.15
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by brianmhunt** [comment]
:crying_cat_face:

**Comment by AsaAyers** [comment]
I'm looking at this, but any additional info would be appreciated. I don't see where `linter` or `linter-jshint` depend on lodash, so I don't know how this is being thrown.

**Comment by mrextreme** [comment]
It threw bucketloads of big red ERROR boxes on the top right corner after updating the plugin, but I did not restart Atom. I'll exit, kill the process, restart, and see if it still happens.

**Comment by brianmhunt** [comment]
The stack trace for me references `linter/lib/linter.coffee:296`, and in particular:

```coffeescript
291   getEditorScopesForPosition: (position) ->
292     try
293       # return a copy in case it gets mutated (hint: it does)
294       @editor.displayBuffer.tokenizedBuffer.scopesForPosition(position).slice()
295     catch
296       # this can throw if the line has since been deleted
297       []
```
Not sure why the stack trace would be bubbling up through this. Will keep digging.

**Comment by steelbrain** [comment]
@brianmhunt did you try a restart?

**Comment by ansballard** [comment]
Had the same issue immediately after updating atom and linter. Updated, opened a js file (using eslint), got that error. Restarted atom, reopened the same js file, linter worked correctly with no errors.

**Comment by mrextreme** [comment]
Yes, and the problem is gone.

**Comment by AsaAyers** [comment]
I think the old `linter` (and maybe `linter-*`) don't shut down properly during the upgrade, so you have old code in-memory. The new `linter` doesn't use `lodash` so it's been uninstalled.

I think restarting atom or `ctrl+alt+r` to reload will fix it.

**Comment by AsaAyers** [comment]
To the next person to encounter this: Please let us know if `View > Reload` (`ctrl+alt+r`) fixes this.

**Comment by brianmhunt** [comment]
@AsaAyers Yes indeed, that fixes it (keyboard binding in my Mac is `alt-shift-cmd-L`).

**Comment by garethbjohnson** [comment]
@mrextreme Thanks for the solution!

**Comment by DavidAwad** [comment]
confirmed from module.js 330 

```javascript
Error: Cannot find module 'lodash'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at LinterCsslint.Linter.getEditorScopesForPosition (/Users/david/.atom/packages/linter/lib/linter.coffee:291:31)
  at LinterCsslint.Linter.computeRange (/Users/david/.atom/packages/linter/lib/linter.coffee:337:5)
  at LinterCsslint.Linter.createMessage (/Users/david/.atom/packages/linter/lib/linter.coffee:16:3)
  at LinterCsslint.<anonymous> (/Users/david/.atom/packages/linter/lib/linter.coffee:235:37)
  at Function.self.forEach (/Users/david/.atom/packages/linter/node_modules/xregexp/xregexp-all.js:542:22)
  at LinterCsslint.Linter.processMessage (/Users/david/.atom/packages/linter/lib/linter.coffee:236:7)
  at /Users/david/.atom/packages/linter/lib/linter.coffee:165:7
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

**Comment by steelbrain** [comment]
@DavidAwad did you try the solution by AsaAyers?

**Comment by MatthewHerbst** [comment]
@AsaAyers 's solution of  `view > Reload` worked for me, though I had to do it via the GUI - neither `alt-shift-cmd-L` nor `ctrl+alt+r` keybinds seemed to work for me.

**Comment by steelbrain** [comment]
Closing as not really a bug but an update issue.
