### ISSUE TITLE
Uncaught TypeError: Invalid Point: (478, NaN)

### ISSUE THREAD

**Issue by jonathanmorley** [AtomLinter/Linter#583]
[Enter steps to reproduce below:]

1. Open a web config
2. Copy in xdt element
3. Click to edit the xdt element

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v1.0.1

### Stack Trace

Uncaught TypeError: Invalid Point: (478, NaN)

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:38

TypeError: Invalid Point: (478, NaN)
    at Function.module.exports.Point.assertValid (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:956:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:944:20)
    at TextBuffer.module.exports.TextBuffer.markRange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:674:46)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1383:41)
    at TextEditor.module.exports.TextEditor.markBufferRange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1269:59)
    at LinterViews.updateBubble (/Users/jmorley/.dotfiles/atom.symlink/packages/linter/lib/linter-views.coffee:90:65)
    at /Users/jmorley/.dotfiles/atom.symlink/packages/linter/lib/editor-linter.coffee:27:37
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextEditor.module.exports.TextEditor.cursorMoved (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1580:27)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-objective-c",
      "language-perl",
      "language-php",
      "dev-live-reload",
      "language-c",
      "package-generator",
      "welcome",
      "styleguide",
      "language-toml"
    ],
    "projectHome": "/Users/jmorley/Code"
  },
  "linter": {
    "subtleLinterErrors": [
      "rubocop"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
language-chef, v0.4.0
language-csharp, v0.6.0
language-docker, v1.1.3
language-fsharp, v0.8.4
language-groovy, v0.4.0
language-powershell, v2.0.1
linter, v1.0.1
linter-foodcritic, v0.3.10
linter-pylint, v0.2.2
linter-rubocop, v0.2.7
linter-xmllint, v0.0.6
pretty-json, v0.3.3
tool-bar, v0.1.8
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
This is a bug in linter provider you're using and not in `linter` itself. You might want to open it on that repo.
