### ISSUE TITLE
Uncaught TypeError: Invalid Point: (6, NaN)

### ISSUE THREAD

**Issue by bretthowell** [AtomLinter/Linter#656]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v1.1.0

### Stack Trace

Uncaught TypeError: Invalid Point: (6, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65

TypeError: Invalid Point: (6, NaN)
  at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:956:13)
  at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:944:20)
  at TextBuffer.module.exports.TextBuffer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:674:46)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1383:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1269:59)
  at /Users/bretthowell/.atom/packages/linter/lib/linter-views.coffee:227:45
  at Set.forEach (native)
  at LinterViews.renderPanel (/Users/bretthowell/.atom/packages/linter/lib/linter-views.coffee:224:15)
  at LinterViews.updateCurrentLine (/Users/bretthowell/.atom/packages/linter/lib/linter-views.coffee:138:8)
  at /Users/bretthowell/.atom/packages/linter/lib/editor-linter.coffee:22:23
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1580:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:56:31
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:270:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:65:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:400:20)
  at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:345:12)
  at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:143:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:175:32)
  at Marker.module.exports.Marker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:185:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:121:31
  at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:683:7)
  at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:119:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1371:23
  at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1571:9)
  at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1370:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:557:25)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
     -0:20.8.0 core:save (atom-text-editor.editor.is-focused)
 10x -0:19.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:16 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "linter-xmllint"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
language-swift, v0.4.0
less-than-slash, v0.6.0
linter, v1.1.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Please note that this is not a bug in Linter itself but it's provider you were using, Please open a bug over to their repo.

**Comment by k2b6s9j** [comment]
He doesn't have any providers installed *and* enabled though...

**Comment by steelbrain** [comment]
@k2b6s9j Then how was the linting triggered and we got the line number of the point but not the char :smiley:

**Comment by k2b6s9j** [comment]
I don't know, that's what's confusing me. If he doesn't have any providers actually providing why would this even happen? And where did the line number even come from?

@bretthowell What where you doing when this happened?

**Comment by bretthowell** [comment]
I had linter-xmllint installed then the errors started. Then I uninstalled
it but didn't restart Atom and thats when this issue occurred.

I uninstalled because there were all kinds of errors being thrown by linter
in a simple XML doc I was testing the package with....

<hello>
  <world>
    <this>
      <is>asdf
      </is>
    </this
  </world>ttss


</hells>
asdf

On Sat, Jun 27, 2015 at 10:27 PM, Kepler Sticka-Jones <
notifications@github.com> wrote:

> I don't know, that's what's confusing me. If he doesn't have any providers
> actually providing why would this even happen? And where did the line
> number even come from?
>
> @bretthowell <https://github.com/bretthowell> What where you doing when
> this happened?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AtomLinter/Linter/issues/656#issuecomment-116195743>.
>



-- 

 [image: Logo] *Brett Howell*
 Main: (724) 4TH DOWN
Direct: (619) 618-0445
Skype: brett.howell
bretth@4thdownsoftware.com

**Comment by steelbrain** [comment]
@bretthowell Would you mind opening this issue over to the xmllint repo?

**Comment by bretthowell** [comment]
Sure.

On Sat, Jun 27, 2015 at 10:32 PM, Steel Brain <notifications@github.com>
wrote:

> @bretthowell <https://github.com/bretthowell> Would you mind opening this
> issue over to the xmllint repo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AtomLinter/Linter/issues/656#issuecomment-116196303>.
>



-- 

 [image: Logo] *Brett Howell*
 Main: (724) 4TH DOWN
Direct: (619) 618-0445
Skype: brett.howell
bretth@4thdownsoftware.com

**Comment by bretthowell** [comment]
https://github.com/AtomLinter/linter-xmllint/issues/22

**Comment by steelbrain** [comment]
:+1:
